backend:
  name: git-gateway
  repo: ico-masters/website
  branch: master
  site_domain: tldrcapital.netlify.com
media_folder: "images/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: false
    delete: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "ID", name: "id", widget: "hidden"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - {label: "Headline", name: "headline", widget: "string", required: false}
      - {label: "Home headline", name: "home_headline", widget: "string", required: false}
      - {label: "Summary", name: "summary", widget: "string", required: false}
      - {label: "Home summary", name: "home_summary", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "CTA", name: "cta", widget: "string", required: false}
      - {label: "CTA page", name: "cta_page", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "services"
    label: "Service"
    folder: "_services"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "services"}
      - {label: "Featured", name: "featured", widget: "boolean", default: "false"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Anchor", name: "anchor", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Testimonials"
        name: "testimonials"
        widget: "list"
        allow_add: true
        default: []
        fields:
          - label: Testimonial
            name:  testimonial
            widget: object
            fields:
              - {label: "First Name",   name: "first_name", widget: "string", required: true}
              - {label: "Last Name",    name: "last_name", widget: "string", required: true}
              - {label: "Avatar",       name: "avatar", widget: "image", required: false}
              - {label: "description",  name: "description", widget: "markdown", required: true}

  - name: "clients"
    label: "Client"
    folder: "_clients"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "clients"}
      - {label: "Featured", name: "featured", widget: "boolean", default: "false"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Company Name", name: "title", widget: "string"}
      - {label: "URL", name: "site_address", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
  - name: "team"
    label: "Team Member"
    folder: "_team"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "team"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Avatar", name: "avatar", widget: "image"}
      - {label: "Role", name: "role", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Twitter", name: "twitter_url", widget: "string", required: false}
      - {label: "Linkedin", name: "linkedin_url", widget: "string", required: false}
  - name: "testimonials"
    label: "Testimonial"
    folder: "_testimonials"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "testimonials"}
      - {label: "Featured", name: "featured", widget: "boolean", default: "false"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Company Name", name: "title", widget: "string"}
      - {label: "Company Person", name: "company_person", widget: "string"}
      - {label: "Quote", name: "quote", widget: "markdown"}
      - {label: "Image", name: "image", widget: "image"}

  - name: "news"
    label: "News"
    folder: "_news"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Permalink", name: "permalink", widget: "hidden", default: '/news/:title'}
      - {label: "ID", name: "id", widget: "hidden", default: 'news'}
      - {label: "Featured", name: "featured", widget: "boolean", default: "false"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "resources"
    label: "Resources"
    folder: "_resources"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "clients"}
      - {label: "Featured", name: "featured", widget: "boolean", default: "false"}
      - {label: "Order", name: "order", widget: "number", valueType: "int"}
      - {label: "Resource Name", name: "title", widget: "string"}
      - {label: "File Size (MB)", name: "file_size", widget: "number"}
      - {label: "File Type", name: "file_type", widget: "string"}
      - {label: "Download URL", name: "download_url", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
  - name: "terms"
    label: "Terms"
    folder: "_terms"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "clients"}
      - {label: "Letter", name: "letter", widget: "string"}
      - {label: "Term", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
